Language = 'Go'
Cmd = './a.out'
Args = []
Reactive = false
TesterPath = 'tools/target/release/tester'
VisPath = 'tools/target/release/vis'
GenPath = 'tools/target/release/gen'
InfilePath = 'tools/in/'
OutfilePath = 'out/'
Jobs = 4
Cloud = false
CompilerURL = 'https://go-compiler-xgep7m6rnq-an.a.run.app/compiler'
Source = 'main.go'
CompileCmd = 'go build -o a.out main.go'
Binary = 'a.out'
tmpBinary = ''
Bucket = 'binarys'
WorkerURL = 'https://worker-xgep7m6rnq-an.a.run.app/worker'
ConcurrentRequests = 100
TimeLimitMS = 3000000

